# Website details
name: Dasper
description: Just a demo
email: hello@ozgrozer.com
author: ozgrozer
lang: en
locale: tr_TR

# Jekyll
paginate: 10
highlighter: rouge
markdown: kramdown
gems: [jekyll-paginate]
timezone: Europe/Istanbul
paginateLabel: page
paginate_path: "page/:num"
permalink: /:categories/:year/:month/:day/:title
baseurl: http://ozgrozer.github.io/dasper

# Includes
addthisId: ""
disqusUsername: ""
googleAnalyticsId: ""

# Search engine verifications
bing: ""
yandex: ""
google: ""

#Sitemap
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/404.html"
    include_posts:
        - "/index.html"
    change_frequency_name: "daily"
    priority_name: "1.00"